const playlist = document.querySelector<HTMLInputElement>("#playlist")
const selectedListText = document.querySelector<HTMLElement>("#selectedList")
const currentMusicName = document.querySelector<HTMLElement>("#currentMusicName")
const deleteListBtn = document.querySelector<HTMLElement>("#deleteList")
const backwardBtn = document.querySelector<HTMLElement>("#backwardBtn")
const playStopBtn = document.querySelector<HTMLElement>("#playStopBtn")
const forwardBtn = document.querySelector<HTMLElement>("#forwardBtn")
const progressBar = document.querySelector<HTMLProgressElement>("#progressBar")
const progressTime = document.querySelector<HTMLElement>("#progressTime")
const selectedVolume = document.querySelector<HTMLElement>("#selectedVolume")
const volumeControl = document.querySelector<HTMLProgressElement>("#volumeControl")
const playlistPopupDragBar: HTMLElement | any = document.querySelector("#playlistRoot #dragBar")
const youtubeListInputPopupDragBar = document.querySelector<HTMLElement>("#youtubeListInputPopup")
const playlistPopup = document.querySelector<HTMLElement>("#playlistRoot")
const youtubeListInputPopup = document.querySelector<HTMLElement>("#youtubeListInputPopup")
const makeListBtn = document.querySelector<HTMLElement>("#makeList")
const uploadFolder = document.querySelector<HTMLElement>("#uploadFolder")
const youtubeListBtn = document.querySelector<HTMLElement>("#youtubeList")
const root = document.querySelector(".root")
let selectedList: string | null = null
let deleteMode: boolean = false
let currentMusic: HTMLAudioElement | null = null
let valuePerSec: number = 0
let timeout: NodeJS.Timeout | any = null
let progressInterval: NodeJS.Timeout | any = null